# Generated by Django 6.0 on 2026-08-20 10:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('genre', models.CharField(blank=True, choices=[('Action', 'action'), ('Comedy', 'comedy'), ('Drama', 'drama'), ('Horror', 'horror'), ('Romance', 'romance'), ('Sci-Fi', 'sci-fi'), ('Thriller', 'thriller'), ('Western', 'western'), ('Animation', 'animation'), ('Adventure', 'adventure'), ('Fantasy', 'fantasy')], max_length=30)),
                ('released_year', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1800), django.core.validators.MaxValueValidator(2026)])),
                ('rating', models.PositiveSmallIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('watched', models.BooleanField(default=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
    ]
