# Generated by Django 6.0 on 2026-08-20 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='released_year',
            new_name='release_year',
        ),
    ]
