# Generated by Django 6.0 on 2026-08-20 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_rename_released_year_movie_release_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(blank=True, choices=[('action', 'Action'), ('comedy', 'Comedy'), ('drama', 'Drama'), ('horror', 'Horror'), ('romance', 'Romance'), ('sci_fi', 'Sci-Fi'), ('thriller', 'Thriller'), ('western', 'Western'), ('animation', 'Animation'), ('adventure', 'Adventure'), ('fantasy', 'Fantasy')], max_length=30),
        ),
    ]
